  [build]
  command = "npm run build"
  publish = "build/client"
  NODE_VERSION = "18"

[functions]
  directory = "build/server"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
